# Basic site settings
title: "Aaron Kermes Portfolio"
description: "Cybersecurity and Instructional Design Portfolio of Aaron Kermes"
theme: jekyll-theme-cayman
markdown: kramdown

# Site navigation links (optional)
nav_links:
  - title: "Home"
    url: "/index.html"
  - title: "About"
    url: "/about.html"
  - title: "Projects"
    url: "/projects.html"
  - title: "Contact"
    url: "/contact.html"

